export enum KarmaReason {
  CONTENT_VALIDATION = 'CONTENT_VALIDATION',
  ORIGINAL_CONTENT = 'ORIGINAL_CONTENT',
  POSITIVE_ENGAGEMENT = 'POSITIVE_ENGAGEMENT',
  MODERATION_HELP = 'MODERATION_HELP',
  TRUTH_CAMPAIGN = 'TRUTH_CAMPAIGN',
  MISINFORMATION = 'MISINFORMATION',
  FAKE_ENGAGEMENT = 'FAKE_ENGAGEMENT',
  DECEPTION = 'DECEPTION',
}

export const KARMA_AMOUNTS: Record<KarmaReason, number> = {
  [KarmaReason.CONTENT_VALIDATION]: 10,
  [KarmaReason.ORIGINAL_CONTENT]: 15,
  [KarmaReason.POSITIVE_ENGAGEMENT]: 5,
  [KarmaReason.MODERATION_HELP]: 20,
  [KarmaReason.TRUTH_CAMPAIGN]: 0, // Variable, set by campaign
  [KarmaReason.MISINFORMATION]: 50,
  [KarmaReason.FAKE_ENGAGEMENT]: 30,
  [KarmaReason.DECEPTION]: 25,
};
